// src/lib/data.ts
// Central data loader. Reads the processed JSON files generated by scripts/process-data.mjs.
// Everything is statically imported into the bundle so deploys are pure static assets.

import basesJson from '../../data/processed/bases.json';
import modsJson from '../../data/processed/mods.json';
import currencyJson from '../../data/processed/currency.json';
import omensJson from '../../data/processed/omens.json';
import seasonJson from '../../data/processed/season.json';
import manifestJson from '../../data/processed/manifest.json';
import weightsJson from '../../data/processed/weights.json';

import type {
  BaseItem,
  Mod,
  Currency,
  Omen,
  Season,
  WeightEntry,
} from './types';

export const bases: BaseItem[] = basesJson as BaseItem[];
export const mods: Mod[] = modsJson as Mod[];
export const currency: Currency[] = currencyJson as Currency[];
export const omens: Omen[] = omensJson as Omen[];
export const season: Season = seasonJson as Season;
export const weights: WeightEntry[] = weightsJson as WeightEntry[];
export const manifest = manifestJson as {
  generatedAt: string;
  season: Season;
  counts: { bases: number; mods: number; currency: number; omens: number };
};

/** Get prefixes and suffixes available for a given base item, filtered by domain + level */
export function getModsForBase(base: BaseItem): { prefix: Mod[]; suffix: Mod[] } {
  const prefix: Mod[] = [];
  const suffix: Mod[] = [];
  for (const m of mods) {
    if (m.domain.length > 0 && !m.domain.includes(base.slot)) continue;
    if (m.type === 'prefix') prefix.push(m);
    else if (m.type === 'suffix') suffix.push(m);
  }
  return { prefix, suffix };
}

/** Filter mods by search query, type, tags, and tier */
export function searchMods(q: string, opts?: { type?: string; tag?: string; tier?: number }): Mod[] {
  const ql = q.toLowerCase().trim();
  return mods.filter((m) => {
    if (opts?.type && m.type !== opts.type) return false;
    if (opts?.tag && !m.tags.includes(opts.tag as never)) return false;
    if (opts?.tier && m.tier !== opts.tier) return false;
    if (!ql) return true;
    return m.name.toLowerCase().includes(ql) || m.tags.some((t) => t.includes(ql));
  });
}

export function searchBases(q: string, slot?: string): BaseItem[] {
  const ql = q.toLowerCase().trim();
  return bases.filter((b) => {
    if (slot && b.slot !== slot) return false;
    if (!ql) return true;
    return b.name.toLowerCase().includes(ql);
  });
}

export const SLOTS = [
  'helmet', 'body_armour', 'gloves', 'boots', 'belt',
  'amulet', 'ring', 'shield', 'quiver', 'focus',
  'weapon_1h', 'weapon_2h',
  'flask', 'charm', 'jewel',
  'waystone', 'tablet', 'relic',
] as const;

export const SLOT_LABELS: Record<string, string> = {
  helmet: 'Helmets',
  body_armour: 'Body Armours',
  gloves: 'Gloves',
  boots: 'Boots',
  belt: 'Belts',
  amulet: 'Amulets',
  ring: 'Rings',
  shield: 'Shields',
  quiver: 'Quivers',
  focus: 'Foci',
  weapon_1h: 'One-Hand Weapons',
  weapon_2h: 'Two-Hand Weapons',
  flask: 'Flasks',
  charm: 'Charms',
  jewel: 'Jewels',
  waystone: 'Waystones',
  tablet: 'Tablets',
  relic: 'Relics',
};
